
repos:
  - repo: https://github.com/psf/black
    rev: 23.10.0  # Latest stable version
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        verbose: true
        args: [--config-file=pyproject.toml]
        additional_dependencies: ['types-requests']
