# Generated by Django 5.1.5 on 2025-01-15 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import drf_oauth_toolkit.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ('drf_oauth_toolkit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='service_name',
            field=models.CharField(
                choices=[('google', 'Google'), ('twitter', 'Twitter')], max_length=50
            ),
        ),
        migrations.CreateModel(
            name='OAuthRequestToken',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'request_token',
                    drf_oauth_toolkit.utils.fields.EncryptedField(max_length=255, unique=True),
                ),
                (
                    'request_token_secret',
                    drf_oauth_toolkit.utils.fields.EncryptedField(max_length=255),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OAuth1Token',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'service_name',
                    models.CharField(
                        choices=[('google', 'Google'), ('twitter', 'Twitter')], max_length=50
                    ),
                ),
                ('oauth_token', drf_oauth_toolkit.utils.fields.EncryptedField(max_length=500)),
                (
                    'oauth_token_secret',
                    drf_oauth_toolkit.utils.fields.EncryptedField(max_length=500),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='oauth1_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('user', 'service_name')},
            },
        ),
    ]
